---
language: python
python: "2.7"

env:
  - KITCHEN_TEST="server-default"
  - KITCHEN_TEST="agent-default"

before_install:
  - curl --version
  - curl --help
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl git python-pip ruby ruby-dev build-essential autoconf
  - gem install bundler
  # Get ansible install
  - curl -s https://raw.githubusercontent.com/AutomationWithAnsible/ansible-setup/master/example/travis-install -o /tmp/travis-ansible-setup.sh

install:
  - bash /tmp/travis-ansible-setup.sh
  - bundle install

script:
    - ansible --version
    - export TRAVIS=True
    - ~/.venv_ansible/v2/venv/bin/pip install netaddr
    - sudo netstat -ntlp
    - bundle exec kitchen test $KITCHEN_TEST
    - sudo netstat -ntlp

after_success:
    - echo "Success"