---

- name: consul services | Get current services
  shell: "ls sv* | sed 's/sv_//g;s/.json//g'"
  changed_when: False
  args:
    chdir: "{{ consul_config_dir }}"
  register: registered_consul_services

- name: consul services | Check if any services are old
  set_fact:
    old_services: "{{ registered_consul_services.stdout_lines | difference(consul_producer_services) }}"

- name: consul services | Ensure old consul services JSON (if any) are deregister
  file:
    path="{{ consul_config_dir }}/sv_{{ item }}.json"
    state="absent"
  with_items: "{{ old_services }}"
  notify:
    - reload consul service

- name: consul services | Ensure consul services JSON are registered
  template:
    src="consul_service.j2"
    dest="{{ consul_config_dir }}/sv_{{ item }}.json"
  with_items:  "{{ consul_producer_services }}"
  notify:
    - reload consul service
